name: Build & Push Docker Image

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}


on:
  push:
    branches:
      - main  # Exécute l'action lorsqu'on pousse sur la branche main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.REPO_NAME }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.REPO_NAME }}
